# compression does not really make sense with node modules
compressionLevel: 0

# react native does not yet support pnp https://yarnpkg.com/features/pnp#incompatible
nodeLinker: node-modules

nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
