description: Restores and saves the node_modules directory
steps:
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
  - run:
      name: Install Dependencies
      command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
  - save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
