description: Restores and saves the node_modules directory
steps:
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - 1-yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
        - 1-yarn-packages-{{ arch }}-
  - run:
      name: Install Dependencies
      command: yarn install --immutable
  - save_cache:
      name: Save Yarn Package Cache
      key: 1-yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}
      paths:
        - .yarn/cache
