when: << pipeline.parameters.run_browserstack_delivery >>
jobs:
  - bump_version:
      context:
        - mattermost
      prepare_delivery: false
  - build_android:
      context:
        - mattermost
        - credentials-repo
        - credentials-lunes
      requires:
        - bump_version
  - build_ios:
      context:
        - mattermost
        - fastlane-match
        - tuerantuer-apple
      requires:
        - bump_version
  - deliver_browser_stack:
      context:
        - mattermost
        - browserstack
      requires:
        - build_android
        - build_ios