when: << pipeline.parameters.run_promote >>
jobs:
  - promote_android:
      context:
        - mattermost
        - tuerantuer-google-play
  - promote_ios:
      context:
        - mattermost
        - tuerantuer-apple
  - notify_promotion:
      context:
        - mattermost
        - deliverino
      requires:
        - promote_android
        - promote_ios
