import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/colors';

export const styles = StyleSheet.create({
  checkEntryButton: {
    width: 192,
    height: 40,
    backgroundColor: COLORS.lunesBlack,
    borderRadius: 20,
    marginBottom: 16,
    paddingVertical: 10,
    marginTop: 40,
  },
  checkEntryLabel: {
    textAlign: 'center',
    color: COLORS.lunesWhite,
    fontFamily: 'SourceSansPro-Semibold',
    fontSize: 14,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  giveUpButton: {
    width: 192,
    height: 40,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    marginBottom: 29,
    borderWidth: 1.5,
    borderColor: COLORS.lunesBlack,
    paddingVertical: 10,
  },
  giveUpLabel: {
    textAlign: 'center',
    color: COLORS.lunesBlack,
    fontFamily: 'SourceSansPro-Semibold',
    fontSize: 14,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  tryLaterButton: {
    display: 'flex',
    flexDirection: 'row',
    width: 105,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  disabledButton: {
    backgroundColor: COLORS.lunesBlackUltralight,
  },
  disabledButtonLabel: {
    color: COLORS.lunesBlackLight,
  },
  nextWordButton: {
    width: 160,
    height: 40,
    backgroundColor: COLORS.lunesBlack,
    borderRadius: 20,
    paddingVertical: 10,
    marginTop: 40,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextWordLabel: {
    textAlign: 'center',
    color: COLORS.lunesWhite,
    fontFamily: 'SourceSansPro-Semibold',
    fontSize: 14,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontWeight: '600',
    marginRight: 8,
  },
});
