# Promote the app from the beta to the production track in the Google Play Store.
docker:
  - image: cimg/android:2024.08.1-node
resource_class: small
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - restore_ruby_cache:
      directory: android
  - run:
      name: '[FL] Play Store Promotion'
      command: bundle exec fastlane android playstore_promote
      working_directory: android
  - notify
