source "https://rubygems.org"

gem "fastlane"

# Exclude problematic versions of activesupport that causes build failures.
gem 'cocoapods', '>= 1.16.2'
gem 'activesupport', '>= 7.2.3.1', '< 8'
gem 'minitest', '>= 5.1', '< 6'
gem 'xcodeproj', '>= 1.27.0'
gem 'concurrent-ruby', '>= 1.3.7'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
