require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Lunes' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  target 'LunesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
    #flipper_post_install(installer)
  #end
end

target 'Lunes-tvOS' do
  # Pods for Lunes-tvOS

  target 'Lunes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
